---
- name: Resetting Hookshot's crypto store
  ansible.builtin.command:
    cmd: |
      {{ devture_systemd_docker_base_host_command_docker }} run
      --rm
      --name={{ matrix_hookshot_container_ident }}-reset-crypto
      --user={{ matrix_user_uid }}:{{ matrix_user_gid }}
      --cap-drop=ALL
      -v {{ matrix_hookshot_base_path }}/config.yml:/config.yml
      {{ matrix_hookshot_docker_image }} yarn start:resetcrypto
  changed_when: false
